kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: preprov-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: my-pre-pv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pre-pv
  annotations:
    pv.kubernetes.io/provisioned-by: daos.csi.storage.gke.io
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: daos.csi.storage.gke.io
    # Modify this to use the zone, filestore instance and share name.
    volumeHandle: "pool1/cont1"
