apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
   - name: daos-sidecar
     imagePullPolicy: Always
     image: gcr.io/cloud-daos-perf-testing/daos-sidecar:v1-dfuse
     volumeMounts:
       - mountPath: /daos-tmp
         name: daos-tmp
       - mountPath: /opt/daos/etc
         name: daos-agent-config
   - name: web-server
     image: nginx
     volumeMounts:
       - mountPath: /usr/share/nginx/html
         name: mypvc
  volumes:
   - name: daos-tmp
     emptyDir:
       sizeLimit: 500Mi
   - name: daos-agent-config
     configMap:
      name: daos-agent
   - name: mypvc
     persistentVolumeClaim:
       claimName: preprov-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: preprov-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: my-pre-pv
  resources:
    requests:
      storage: 1Ti
