apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: daos.csi.storage.gke.io
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  requiresRepublish: true
  tokenRequests:
    - audience: <project-id>.svc.id.goog