apiVersion: v1
data:
  daos_agent.yml: |-
    access_points: ["10.128.0.7"] # change to daos server IP address
    transport_config:
      allow_insecure: true
    fabric_ifaces:
    - numa_node: 0
      devices:
      - iface: eth0
        domain: eth0
  daos_control.yml: |-
    hostlist: ["10.128.0.7"] # change to daos server IP address
    transport_config:
      allow_insecure: true
kind: ConfigMap
metadata:
  name: daos-agent
  namespace: default