---
##### Node Service Account, Roles, RoleBindings
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daoscsi-node-sa
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: csi-daos-node
value: 900001000
globalDefault: false
description: "This priority class should be used for the Cloud Storage FUSE CSI driver node deployment only."
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daos-csi-publisher-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: daos-csi-publisher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: daos-csi-publisher-role
subjects:
  - kind: ServiceAccount
    name: daoscsi-node-sa